const products = [
  {
    id: "1",
    imgSrc: "/assets/images/image-waffle-desktop.jpg",
    title: "Waffle with Berries",
    description: "Waffle",
    price: "$6.50",
  },
  {
    id: "2",
    imgSrc: "/assets/images/image-creme-brulee-desktop.jpg",
    title: "Chocolate Waffle",
    description: "Waffle",
    price: "$7.00",
  },
  {
    id: "3",
    imgSrc: "/assets/images/image-macaron-desktop.jpg",
    title: "Strawberry Waffle",
    description: "Waffle",
    price: "$6.75",
  },
  {
    id: "4",
    imgSrc: "/assets/images/image-tiramisu-desktop.jpg",
    title: "Waffle with Berries",
    description: "Waffle",
    price: "$6.50",
  },
  {
    id: "5",
    imgSrc: "/assets/images/image-baklava-desktop.jpg",
    title: "Chocolate Waffle",
    description: "Waffle",
    price: "$7.00",
  },
  {
    id: "6",
    imgSrc: "/assets/images/image-meringue-desktop.jpg",
    title: "Strawberry Waffle",
    description: "Waffle",
    price: "$6.75",
  },
  {
    id: "7",
    imgSrc: "/assets/images/image-cake-desktop.jpg",
    title: "Waffle with Berries",
    description: "Waffle",
    price: "$6.50",
  },
  {
    id: "8",
    imgSrc: "/assets/images/image-brownie-desktop.jpg",
    title: "Chocolate Waffle",
    description: "Waffle",
    price: "$7.00",
  },
  {
    id: "9",
    imgSrc: "/assets/images/image-panna-cotta-desktop.jpg",
    title: "Strawberry Waffle",
    description: "Waffle",
    price: "$6.75",
  },
  // Add 5 more products here as needed
];
